services:
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    networks:
      - trackspense-net

networks:
  trackspense-net:
    driver: bridge
