#PostgreSQL Config
spring.datasource.url=jdbc:postgresql://dpg-d7go70beo5us739hqukg-a.oregon-postgres.render.com/trackspense
spring.datasource.username=trackspense_user
spring.datasource.password=VvDtcQXZ9gtok5EQKZwmyqBqTGj8UMmf