#PostgreSQL Config
spring.datasource.url=jdbc:postgresql://dpg-d7go70beo5us739hqukg-a.oregon-postgres.render.com/trackspense
spring.datasource.username=trackspense_user
spring.datasource.password=VvDtcQXZ9gtok5EQKZwmyqBqTGj8UMmf

#Email Config
#spring.mail.host=smtp.gmail.com
#spring.mail.port=465
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true

#App URLs
app.activation.url=${TRACKSPENSEV2_BACKEND_URL}
trackspense.frontend.url=${TRACKSPENSEV2_FRONTEND_URL}
server.servlet.context-path=/api/v2