#MySQL Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/trackspensev2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kel3604luv!}
server.servlet.context-path=/api/v2

#JPA Configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Email Config
#mailjet.api.key=2cacb8a1435584f739fe0a2586eb0f0a
#mailjet.secret.key=1c7307e752f07e0e5922794643f26a74
#mailjet.sender.email=a.mans.opinion01@gmail.com
#mailjet.sender.name=TrackSpense
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME:a.mans.opinion01@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:jihkikxtblvrxnnc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

jwt.secret=${JWT_SECRET:2KJMUD67H+IB1IDhfUeKr85imNRnXhGWBmlQeYwenw8=}
jwt.expiration-ms=3600000

trackspense.frontend.url=http://localhost:5173

app.activation.url=http://localhost:8080

#spring.profiles.active=prod