#PostgreSQL Config
spring.datasource.url=jdbc:postgresql://dpg-d7go70beo5us739hqukg-a.oregon-postgres.render.com/trackspense
spring.datasource.username=trackspense_user
spring.datasource.password=VvDtcQXZ9gtok5EQKZwmyqBqTGj8UMmf

#Email Config
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_FROM_EMAIL}

#App URLs
app.activation.url=${TRACKSPENSEV2_BACKEND_URL}
trackspense.frontend.url=${TRACKSPENSEV2_FRONTEND_URL}